# Generated by Django 4.2 on 2024-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
