# Generated by Django 4.2 on 2024-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
        ),
    ]
